
@startuml
== AjouterMembresAuCanal ==

boundary MembreCanalComponent
participant JwtTokenAuthFilter
control DispatcherServlet 

MembreCanalComponent -> JwtTokenAuthFilter : Post /api/canal/{idCanal}/membre/{idMembre}
JwtTokenAuthFilter --> JwtTokenAuthFilter : check if token exists
==Token not found ==
JwtTokenAuthFilter --> MembreCanalComponent : error message 
==Token OK ==
JwtTokenAuthFilter -> DispatcherServlet : Post /api/canal/{idCanal}/membre/{idMembre}
DispatcherServlet -> PersonneRestController : Post /api/canal/{idCanal}/membre/{idMembre}
PersonneRestController --> DispatcherServlet : JSON<Membres> ou null ou Exception
DispatcherServlet --> MembreCanalComponent : JSON<Membres>
DispatcherServlet --> MembreCanalComponent : response 400
@enduml