== listerMembresDuCanal ==

@startuml
boundary CanalComponent
participant JwtTokenAuthFilter
control DispatcherServlet 
control PersonneController 

CanalComponent -> JwtTokenAuthFilter : GET /api/canal/{id_canal}
JwtTokenAuthFilter -> JwtTokenAuthFilter : check if token exists
==Token not found ==
JwtTokenAuthFilter -> CanalComponent : error message 
==Token OK ==
JwtTokenAuthFilter -> DispatcherServlet : GET /api/canal/{id_canal}
DispatcherServlet -> PersonneController : GET /api/canal/{id_canal}
PersonneController -> DispatcherServlet : JSON<MembreDto>
DispatcherServlet -> MemebreCanalComponent : JSON<MembreDto>
@enduml