== listerMembresDuCanal ==

@startuml

boundary CanalComponent
participant MemebreCanalComponent
participant JwtTokenAuthFilter
control DispatcherServlet 
control PersonneRestController 

CanalComponent -> JwtTokenAuthFilter : GET /api/canal/{id_canal}
JwtTokenAuthFilter -> JwtTokenAuthFilter : check if token exists
==Token not found ==
JwtTokenAuthFilter -> CanalComponent : error message 
==Token OK ==
JwtTokenAuthFilter -> DispatcherServlet : GET /api/canal/{id_canal}
DispatcherServlet -> PersonneRestController : GET /api/canal/{id_canal}
PersonneRestController -> DispatcherServlet : JSON<MembreDto>
DispatcherServlet -> MemebreCanalComponent : JSON<MembreDto>
@enduml