== listerCanauxById ==

@startuml
boundary CanauxComponent
participant JwtTokenAuthFilter
control DispatcherServlet 
control CanalController 


CanauxComponent -> JwtTokenAuthFilter : Get /api/canaux/{idLogin} 
JwtTokenAuthFilter --> JwtTokenAuthFilter : check if token exists
==Token not found ==
JwtTokenAuthFilter --> CanauxComponent : error message 
==Token OK ==
JwtTokenAuthFilter -> DispatcherServlet : Get /api/canaux/{idLogin}
DispatcherServlet -> CanalController : Get /api/canaux/{idLogin}
CanalController --> DispatcherServlet : JSON<CanalDto> ou null ou Exception
DispatcherServlet --> CanauxComponent : JSON<CanalDto>
DispatcherServlet --> CanauxComponent : response 500/400
@enduml